[package]
name = "chipioindustries/lithium"
description = "A fake network call that can simulate errors and latency."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Llama = "freddylist/llama@1.1.1"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"